# Generated by Django 3.0 on 2020-01-05 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=50)),
                ('category', models.CharField(default='', max_length=50)),
                ('subcategory', models.CharField(default='', max_length=50)),
                ('desc', models.TextField(max_length=200)),
                ('pub_date', models.DateField()),
                ('slug', models.CharField(default='', max_length=150)),
                ('author', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='shop/images')),
            ],
        ),
    ]
