# Generated by Django 3.0 on 2020-01-05 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200101_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.TextField(max_length=200),
        ),
    ]
